#!/bin/sh

cd "$(dirname "$0")/.."

test -z "$NODE_ENV" &&
  export NODE_ENV='development'

if [ "$NODE_ENV" = "development" ]; then
  $(which forever) -f config/forever/development.json
else
  $(which forever) start config/forever/production.json
fi
