#!/bin/sh

cd "$(dirname "$0")/.."

echo "Uninstalling itunes-api..."
forever stop itunes-api > /dev/null 2>&1
launchctl unload ~/Library/LaunchAgents/org.itunes-api.plist
rm ~/Library/LaunchAgents/org.itunes-api.plist
